import sys
import os

Import('program_env')
Import('append_lib')
Import('append_includes')

loader_env = program_env.Clone()

append_includes(loader_env, ['PTHREAD'])
append_lib(loader_env, ['EXR', 'ZLIB', 'PTHREAD', 'MISC', 'PYTHON'])

loader_env.Prepend (LIBPATH = [ '../integrators', '../yafraycore'] )
loader_env.Append(LIBS = ['${YF_CORELIB}'])

eclipse_files = ['aergia.cpp', 
                 'eclipse.cpp', 
                 'pythoninterface.cpp', 
                 'settings.cpp', 
                 'eclight.cpp',
                 'ecrenderenvironment.cpp',
                 'utils.cpp',
                 'ecgeometry.cpp',
                 'ecscene.cpp',
                 'ecmaterial.cpp',
                 'ecintegrator.cpp',
                 'ecbuffer.cpp',
                 'ecmesh.cpp',
                 'ecfilm.cpp',
                 'eccamera.cpp' ]

eclipseRay=loader_env.Program (target='eclipseRay', source=eclipse_files)
#eclipseRayMSVC = loader_env.MSVSProject(target='eclipseRay',source=eclipse_files, variant='Release')






