import sys

#Import('config')
Import('plugin_env')
Import('append_includes')

backg_env = plugin_env.Clone();

backg_env.Append (LIBS = ['bglight'])
backg_env.Append (LIBPATH = ['../lights'])
append_includes(backg_env, ['PTHREAD'])

sunsky=backg_env.SharedLibrary (target='sunsky', source=['sunsky.cc', 'sunspectrum.cc'])
backg_env.Install('${YF_PLUGINPATH}',sunsky)

textureback=backg_env.SharedLibrary (target='textureback', source=['textureback.cc'])
backg_env.Install('${YF_PLUGINPATH}',textureback)

gradientback=backg_env.SharedLibrary (target='gradientback', source=['gradientback.cc'])
backg_env.Install('${YF_PLUGINPATH}',gradientback)

backg_env.Install('${YF_PACKPATH}${YF_PLUGINPATH}',[gradientback, textureback, sunsky])
backg_env.Alias('install_backg','${YF_PLUGINPATH}')
